### ISSUE TITLE
Error when executing NPM command

### ISSUE THREAD

**Issue by jlenon7** [williamhaw/setup-wiremock-action#8]
Hey @williamhaw. Thank you so much for developing this package, I haven't found a way to run Wiremock using the Github Actions services.

I'm trying to run the `npm run test:coverage` command, but I'm getting this error:

<img width="1046" alt="Screenshot 2022-12-17 at 01 00 26" src="https://user-images.githubusercontent.com/52840235/208222985-3f56bca3-643e-42da-b942-11c289f002b3.png">

I haven't cloned the code to check, but I think that the problem might be at the [`runAPITests`](https://github.com/williamhaw/setup-wiremock-action/blob/master/index.js#L109
) function.

**Comment by williamhaw** [comment]
yup I have reproduced this issue in CI, let me look into a fix tonight.

**Comment by jlenon7** [comment]
I also have tried to use just a `npm test` command, but my tests are failing with `ECONNREFUSED` error:

<img width="424" alt="Screenshot 2022-12-17 at 08 56 20" src="https://user-images.githubusercontent.com/52840235/208240695-11a4857a-8660-42cf-952c-094a00416666.png">

You can check the pipeline [here](https://github.com/AthennaIO/Common/actions/runs/3718388074/jobs/6306550218), maybe it could help.

**Comment by williamhaw** [comment]
hi @jlenon7 please try out release v0.1.3
